export const questions = [
  {
    question: "What is your favorite color?",
    answer1: "red/pink/orange",
    answer1Total: "1",
    answer2: "blue/purple/green",
    answer2Total: "3",
    answer3: "black/white/neutrals",
    answer3Total: "2",
  },
  {
    question: "Which word best describes you?",
    answer1: "Extrovert",
    answer1Total: "1",
    answer2: "Introvert",
    answer2Total: "2",
    answer3: "Ambivert",
    answer3Total: "3",
  },
  {
    question: "Where would you prefer to live?",
    answer1: "A big city",
    answer1Total: "1",
    answer2: "A small town or suburb",
    answer2Total: "3",
    answer3: "In the middle of nowhere",
    answer3Total: "2",
  },
  {
    question: "What type of food is the best?",
    answer1: "Mexican food",
    answer1Total: "2",
    answer2: "Italian food",
    answer2Total: "1",
    answer3: "Korean food",
    answer3Total: "3",
  },
  {
    question: "What kind of pet is most ideal?",
    answer1: "A calm and low-maintainence pet like a cat or lizard",
    answer1Total: "3",
    answer2: "A high energy and clingy pet like a puppy",
    answer2Total: "2",
    answer3: "No pets are the best pets",
    answer3Total: "1",
  },
  {
    question: "Do you leave your door open while you sleep?",
    answer1: "Yes?",
    answer1Total: "2",
    answer2: "...No",
    answer2Total: "3",
    answer3: "I don't want to answer",
    answer3Total: "1",
  },
  {
    question: "How quickly do you answer texts?",
    answer1: "Immediately or as soon as I can",
    answer1Total: "1",
    answer2: "At least by the end of the day",
    answer2Total: "2",
    answer3: "Give me 3-5 business days...if I still remember by then",
    answer3Total: "3",
  },
];
